export const register = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Bienvenido a FindBook!!</h1><h4>Nos alegra que estés aquí. FindBook te brinda una gran variedad de libros para que puedas comprar. Tambien tendras la posibilidad de vender tus libros!!!</h4><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://i.postimg.cc/cLv51RqG/book-removebg-preview.png'>FindBook</a></td></tr></table>";

export const registerGoogle = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Bienvenido a FindBook!!</h1><h4>Nos alegra que estés aquí. FindBook te brinda una gran variedad de libros para que puedas comprar. Tambien tendras la posibilidad de vender tus libros!!!</h4><h4>DATOS DE ACCESO:</h4><h5>Correo: ${EMAIL}</h5><h5>Password: ${PASSWORD}</h5><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://i.postimg.cc/cLv51RqG/book-removebg-preview.png'>FindBook</a></td></tr></table>";

export const paymentSucces = "<div style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><div style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></div><div style={{display: 'flex', flexDirection:'column',}}><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Tu compra fue realizada con éxito!!</h1><h4>Tu compra fue realizada correctamente con un monto de USD$${precio}</h4><div style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://i.postimg.cc/cLv51RqG/book-removebg-preview.png'>FindBook</a></div></div></div>";

export const compra = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Aparecio un comprador!!</h1><h4>te han comprado {QUANTITY} libros de {BOOKNAME}. Total USD${PRECIO}.</h4><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://i.postimg.cc/cLv51RqG/book-removebg-preview.png'>FindBook</a></td></tr></table>";

export const comment = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Alguien comentó tu publicación!</h1><h4>El usuario {USER} comentó tu libro {BOOK}.</h4><h5>{COMENTARIO}</h5><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://i.postimg.cc/cLv51RqG/book-removebg-preview.png'>FindBook</a></td></tr></table>";
