export const register = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><td><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Bienvenido a FindBook!!</h1><h4>Nos alegra que estés aquí. FindBook te brinda una gran variedad de libros para que puedas comprar. Tambien tendras la posibilidad de vender tus libros!!!</h4></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const registerGoogle = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><td><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Bienvenido a FindBook!!</h1><h4>Nos alegra que estés aquí. FindBook te brinda una gran variedad de libros para que puedas comprar. Tambien tendras la posibilidad de vender tus libros!!!</h4><h4>DATOS DE ACCESO:</h4><h5>Correo: ${EMAIL}</h5><h5>Password: ${PASSWORD}</h5></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const paymentSucces = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><td><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Tu compra fue realizada con éxito!!</h1><h4>Tu compra fue realizada correctamente con un monto de USD$${precio}</h4></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const compra = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><td><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Aparecio un comprador!!</h1><h4>te han comprado EL libro de {BOOKNAME}. Total USD${PRECIO}.</h4><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/paneluser/detailsale/{COMPRA_ID}'>ver detalle</a></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const comment = "<table style={{background: '#faf8f2', fontFamily: 'serif', height: ['35rem'], width: ['35rem'] }}><tr style={{background: '#f0ede5',  height: ['8rem']}}><img style={{height: ['15rem'], marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex', flexDirection:'column',}}><td><h1 style={{height: ['8rem'],display: 'flex', flexDirection:'column', justifyContent: 'center'}}>Alguien comentó tu publicación!</h1><h4>{USER} comentó tu libro {BOOK}.</h4><h5>{COMENTARIO}</h5><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/detail/{BOOK_ID}'>ver publicación</a></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const deleteAccount = "<table style={{background: '#faf8f2'; fontFamily: 'serif'; height: ['35rem']; width: ['35rem'] }}><tr style={{background: '#f0ede5';  height: ['8rem']}}><img style={{height: ['15rem']; marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex'; flexDirection:'column',}}><td><h1 style={{height: ['8rem']; display: 'flex'; flexDirection:'column'; justifyContent: 'center'}}>Eliminacion de cuenta</h1><h4>Has eliminado tu cuenta, {EMAIL}. Lamentamos que te vayas de nuestra comunidad. Si tuviste algun problema, puedes contactarnos. <a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/contacto'>Contactar</a></h4></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const banAccont = "<table style={{background: '#faf8f2'; fontFamily: 'serif'; height: ['35rem']; width: ['35rem'] }}><tr style={{background: '#f0ede5';  height: ['8rem']}}><img style={{height: ['15rem']; marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex'; flexDirection:'column',}}><td><h1 style={{height: ['8rem']; display: 'flex'; flexDirection:'column'; justifyContent: 'center'}}>Cuenta suspendida</h1><h4>Hemos suspendido tu cuenta, {EMAIL}, por tiempo indeterminado. Si crees que hemos cometido un error, no dudes en contactarnos para que nos ocupemos de tu caso. <a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/contacto'>Contactar</a></h4></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";

export const permaBanAccont = "<table style={{background: '#faf8f2'; fontFamily: 'serif'; height: ['35rem']; width: ['35rem'] }}><tr style={{background: '#f0ede5';  height: ['8rem']}}><img style={{height: ['15rem']; marginTop: ['-4rem']}} src='https://i.postimg.cc/90Hmmmgy/book-removebg-preview.png' alt='Not found'></img></tr><tr style={{display: 'flex'; flexDirection:'column',}}><td><h1 style={{height: ['8rem']; display: 'flex'; flexDirection:'column'; justifyContent: 'center'}}>Cuenta suspendida permanentemente</h1><h4>Hemos suspendido tu cuenta, {EMAIL}, de manera permanente. Si crees que hemos cometido un error, no dudes en contactarnos para que nos ocupemos de tu caso. <a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/contacto'>Contactar</a></h4></td></tr><tr><td style={{ height: ['8rem'], display: 'flex', flexDirection:'column', justifyContent: 'center'}}><a style={{textDecoration: 'none'}} href='https://findbookapp.netlify.app/'>FindBook</a></td></tr></table>";